[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dimensions = { columns = 130, lines = 35 }
dynamic_padding = false
opacity = 1
padding = { x = 1, y = 1 }
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = false

[terminal]
shell = "wsl -d archlinux"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"


[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

[colors.normal]
black = '0x090618'
blue = '0x7e9cd8'
cyan = '0x6a9589'
green = '0x76946a'
magenta = '0x957fb8'
red = '0xc34043'
white = '0xc8c093'
yellow = '0xc0a36e'

[colors.bright]
black = '0x727169'
blue = '0x7fb4ca'
cyan = '0x7aa89f'
green = '0x98bb6c'
magenta = '0x938aa9'
red = '0xe82424'
white = '0xdcd7ba'
yellow = '0xe6c384'
